"""Showcase Builder for KBK — generates Read-Only Confluence space.

Creates a single attractive index page with summaries and links to originals.
"""
from __future__ import annotations
import json
import base64
import urllib.request
from datetime import datetime
from typing import Optional

from kbk.store import KnowledgeStore
from kbk.config import KBKConfig


class ShowcaseBuilder:
    """Builds a Read-Only Confluence showcase page from the KBK index.

    Groups documents by collection with expand/collapse sections.
    Each entry has: LLM summary + tag badges + link to original.
    """

    def __init__(self, store: KnowledgeStore, config: KBKConfig):
        self.store = store
        self.config = config

    def _confluence_headers(self) -> dict:
        auth = base64.b64encode(f"{self.config.confluence_token}:".encode()).decode()
        return {
            "Authorization": f"Basic {auth}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _confluence_request(self, method: str, path: str, data: dict = None) -> Optional[dict]:
        url = f"{self.config.confluence_url}/rest/api{path}"
        body = json.dumps(data).encode() if data else None
        req = urllib.request.Request(url, data=body, headers=self._confluence_headers(), method=method)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except Exception:
            return None

    def _generate_storage_format(self, stats: dict) -> str:
        """Generate Confluence Storage Format HTML."""
        cols = stats.get("collections", {})
        total = stats.get("total", 0)
        updated = datetime.now().strftime("%Y-%m-%d %H:%M")

        sections = []
        # Banner
        sections.append(
            f'<ac:structured-macro ac:name="info">'
            f'<ac:rich-text-body>'
            f'<p>🤖 This page is auto-generated by <strong>Knowledge Base Kit</strong>. '
            f'Last updated: {updated}. Do not edit manually.</p>'
            f'</ac:rich-text-body></ac:structured-macro>'
        )

        # Summary
        sections.append(f"<h2>Index Overview</h2>")
        sections.append(f"<p><strong>{total}</strong> indexed chunks across <strong>{len(cols)}</strong> collections.</p>")

        # Collections
        for col_name, count in sorted(cols.items()):
            if count == 0:
                continue
            chunks = self.store.list_chunks(collection=col_name, limit=100)
            if not chunks:
                continue

            sections.append(f'<ac:structured-macro ac:name="expand">')
            sections.append(f'<ac:parameter ac:name="title">📁 {col_name.capitalize()} ({count} chunks)</ac:parameter>')
            sections.append(f'<ac:rich-text-body>')
            sections.append(f'<table><colgroup><col/><col/></colgroup><tbody>')

            for c in chunks[:50]:
                tags_html = " ".join(
                    f'<ac:structured-macro ac:name="status">'
                    f'<ac:parameter ac:name="colour">Blue</ac:parameter>'
                    f'<ac:parameter ac:name="title">{t}</ac:parameter>'
                    f'</ac:structured-macro>'
                    for t in c.tags[:5]
                )
                summary = c.summary[:200] + "..." if len(c.summary) > 200 else c.summary
                link = f'<a href="{c.source_url}">🔗 Original</a>' if c.source_url else ""
                sections.append(
                    f'<tr><td><strong>{summary}</strong><br/>{tags_html}</td>'
                    f'<td>{link}</td></tr>'
                )

            sections.append(f'</tbody></table>')
            sections.append(f'</ac:rich-text-body></ac:structured-macro>')
            sections.append('<br/>')

        return "\n".join(sections)

    def build(self) -> str:
        """Build the showcase and push to Confluence."""
        stats = self.store.get_stats()
        storage = self._generate_storage_format(stats)
        title = f"KBK Knowledge Index ({datetime.now().strftime('%Y-%m-%d')})"

        # Check if page exists
        pages = self._confluence_request(
            "GET",
            f"/content?spaceKey={self.config.showcase_space}&title={urllib.parse.quote(title)}&expand=version"
        )
        existing_id = None
        current_version = 0
        if pages and pages.get("results"):
            existing_id = pages["results"][0]["id"]
            current_version = pages["results"][0].get("version", {}).get("number", 0)

        data = {
            "type": "page",
            "title": title,
            "space": {"key": self.config.showcase_space},
            "body": {"storage": {"value": storage, "representation": "storage"}},
            "version": {"number": current_version + 1},
        }

        if existing_id:
            result = self._confluence_request("PUT", f"/content/{existing_id}", data)
        else:
            result = self._confluence_request("POST", "/content", data)

        if result:
            return result.get("_links", {}).get("base", self.config.confluence_url) + \
                   result.get("_links", {}).get("webui", "")
        return "Failed to create showcase page"

    def build_markdown(self) -> str:
        """Generate markdown version of showcase (for local preview)."""
        stats = self.store.get_stats()
        updated = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines = [
            f"# KBK Knowledge Index",
            f"",
            f"> 🤖 Auto-generated by Knowledge Base Kit. Last updated: {updated}",
            f"",
            f"**{stats['total']}** indexed chunks across **{len(stats['collections'])}** collections.",
            f"",
        ]
        for col_name, count in sorted(stats["collections"].items()):
            if count == 0:
                continue
            chunks = self.store.list_chunks(collection=col_name, limit=50)
            lines.append(f"## 📁 {col_name.capitalize()} ({count} chunks)")
            lines.append("")
            for c in chunks[:50]:
                tags = f" `{'` `'.join(c.tags[:5])}`" if c.tags else ""
                link = f" [🔗]({c.source_url})" if c.source_url else ""
                summary = c.summary[:200] + "..." if len(c.summary) > 200 else c.summary
                lines.append(f"- {summary}{tags}{link}")
            lines.append("")
        return "\n".join(lines)
